### ISSUE TITLE
update version at general repository?

### ISSUE THREAD

**Issue by slwu89** [SupplyChef/SupplyChainOptimization.jl#2]
The version of the general repo is 0.1.0 (https://juliahub.com/ui/Packages/SupplyChainOptimization/bPrlI/0.1.0) but the one on GitHub is 0.1.1, there are some problems regarding the compat for HiGHS in 0.1.0, it would be nice if the package in the general repo could be updated to resolve those.

**Comment by SupplyChef** [comment]
I updated the dependencies of the package to the latest versions of HiGHS and JuMP. Please let me know if you encounter any other issues.

**Comment by slwu89** [comment]
Thanks @SupplyChef! It is all working great now.
